# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-10 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('addr', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=100)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HospitalScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=3, max_digits=4)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_detail', to='recommendation.Hospital')),
            ],
        ),
    ]
