# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-25 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_hospitalcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre1', models.IntegerField()),
                ('pre2', models.IntegerField()),
                ('pre3', models.IntegerField()),
                ('pre4', models.IntegerField()),
                ('pre5', models.IntegerField()),
                ('ena1', models.IntegerField()),
                ('ena2', models.IntegerField()),
                ('ena3', models.IntegerField()),
                ('need1', models.IntegerField()),
                ('need2', models.IntegerField()),
                ('need3', models.IntegerField()),
                ('service1', models.IntegerField()),
                ('service2', models.IntegerField()),
                ('service3', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.Hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.UserData')),
            ],
        ),
        migrations.AlterField(
            model_name='hospitalscore',
            name='hospital',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_score', to='recommendation.Hospital'),
        ),
    ]
