# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-11 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_hospital_hospitalscore'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hospital',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='hospitalscore',
            name='score',
        ),
        migrations.AddField(
            model_name='hospitalscore',
            name='count_con',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospitalscore',
            name='count_ec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospitalscore',
            name='count_oth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospitalscore',
            name='count_qua',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospitalscore',
            name='count_soc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospitalscore',
            name='count_tem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospitalscore',
            name='score_con',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='hospitalscore',
            name='score_ec',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='hospitalscore',
            name='score_oth',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='hospitalscore',
            name='score_qua',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='hospitalscore',
            name='score_soc',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='hospitalscore',
            name='score_tem',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='hospitalscore',
            name='total_WOM',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wordscore',
            name='type',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
